### ISSUE TITLE
installing and test question

### ISSUE THREAD

**Issue by caiquanyou** [almaan/stereoscope#20]
I install and run the test but get teh error:
dean@67754e316b22:~$ stereoscope test
Traceback (most recent call last):
  File "/home/dean/.local/bin/stereoscope", line 11, in <module>
    load_entry_point('stereoscope==0.3', 'console_scripts', 'stereoscope')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dean/.local/lib/python3.6/site-packages/stereoscope-0.3-py3.6.egg/stsc/__main__.py", line 4, in <module>
    from stsc.run import run
  File "/home/dean/.local/lib/python3.6/site-packages/stereoscope-0.3-py3.6.egg/stsc/run.py", line 17, in <module>
    import stsc.fit as fit
  File "/home/dean/.local/lib/python3.6/site-packages/stereoscope-0.3-py3.6.egg/stsc/fit.py", line 16, in <module>
    import stsc.datasets as D
  File "/home/dean/.local/lib/python3.6/site-packages/stereoscope-0.3-py3.6.egg/stsc/datasets.py", line 14, in <module>
    import stsc.utils as utils
  File "/home/dean/.local/lib/python3.6/site-packages/stereoscope-0.3-py3.6.egg/stsc/utils.py", line 17, in <module>
    import stsc.datasets as D
AttributeError: module 'stsc' has no attribute 'datasets'

**Comment by ramonvidal** [comment]
Same issue here :(

**Comment by almaan** [comment]
Hello to both of you,

from your output @caiquanyou I take it that you are using Python 3.6, now I do not have the same type of information for you @ramonvidal but it would be my guess that such might be the case for you as well. I believe that the issues you are experiencing are due to a discrepancy between python versions with respect to how they handle imports of submodules, (see [here](https://stackoverflow.com/questions/62524794/python-submodule-importing-correctly-in-python-3-7-but-not-3-6) for more information). I managed to reproduce the error in a 3.6.4 environment, but not 3.7 or 3.8, which further supports my suspicions. 

My advice would be to upgrade your python versions, if you don't want to do this on a system level - then creating a conda environment with version >= 3.7 would be an alternative.

I will try to update the imports in order to make it compatible for lower python versions as well, but this might take a couple of days - hence the fastest solution would be the one mentioned above (which I would recommend in any case).

Best
Alma

**Comment by ramonvidal** [comment]
Hi @almaan , you are right, mine is also 3.6. I temporary disabled the error by commenting only [this line](https://github.com/almaan/stereoscope/blob/master/stsc/utils.py#L17). The code run and generated the expected outputs even though you have the same import on other files like in the run.py.

**Comment by almaan** [comment]
Thanks for the fast response @ramonvidal, then I feel fairly confident in attributing this error to the aforementioned cause. I'll get to work on it as soon as time permits me to, hopefully I can push some updates by the end of the week. I'm also afraid to say that even though the test ran "successfully" after commenting out the referenced line, you most likely will not be able to run any of the other modules and execute your analysis while this problem remains.

I'll let you know when this has been taken care of!

**Comment by ramonvidal** [comment]
Thanks a lot @almaan

**Comment by caiquanyou** [comment]
Thanks a lot @almaan，I upgrade the python3.6 to 3.7 and it is successfully installed and test work!

**Comment by ramonvidal** [comment]
It worked here as well with python 3.7. Thanks to you all :)
