### ISSUE TITLE
stereoscope test Error

### ISSUE THREAD

**Issue by yunbokai** [almaan/stereoscope#34]
Hi,
    I use `python -c "import stsc; print(stsc.__version__)"` and get the version 0.3.1.However, When i use the code `stereoscope test`, the Error is 
![c41068087b82a067bc1a7eac39ab9bab](https://user-images.githubusercontent.com/94819980/222048869-ec462987-639a-49b5-9768-6019fb7d6a62.png)

`(stereoscope) D:\stereoscope\stereoscope>python -c "import stsc; print(stsc.__version__)"
stereoscope : 0.3.1
(stereoscope) D:\stereoscope\stereoscope>stereoscope test
Traceback (most recent call last):
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\Scripts\stereoscope-script.py", line 33, in <module>
    sys.exit(load_entry_point('stereoscope==0.3.1', 'console_scripts', 'stereoscope')())
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\Scripts\stereoscope-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\lib\site-packages\stereoscope-0.3.1-py3.8.egg\stsc\__main__.py", line 4, in <module>
    from stsc.run import run
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\lib\site-packages\stereoscope-0.3.1-py3.8.egg\stsc\run.py", line 9, in <module>
    import torch as t
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\lib\site-packages\torch-1.13.1-py3.8-win-amd64.egg\torch\__init__.py", line 779, in <module>
    from .serialization import save, load
  File "C:\Users\yunsy\anaconda3\envs\stereoscope\lib\site-packages\torch-1.13.1-py3.8-win-amd64.egg\torch\serialization.py", line 18, in <module>
    from typing_extensions import TypeAlias
**ModuleNotFoundError: No module named 'typing_extensions**'`

Here is my version 
![index](https://user-images.githubusercontent.com/94819980/222049148-9c15927e-c16e-4312-865b-a4b529ebfedb.png)

    **My python is 3.8. I use the python in Windows by anaconda.**
    Thanks a lot!

**Comment by yunbokai** [comment]
I finished package installation by three futher steps:
`pip install typing-extensions==4.1.1
pip install zipp
pip install colorama`
If anyone got the same problem, it may help .

**Comment by YangXuuu** [comment]
As a similar error, I got "zsh: illegal hardware instruction  stereoscope test" when testing. BTW I am using MacBook Pro M1
